[2023-07-15T16:38:43.028-0400] {processor.py:157} INFO - Started process (PID=35072) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:38:43.031-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:38:43.031-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:38:43.031-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:38:43.051-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:38:43.051-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:38:43.051-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:38:43.051-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:38:43.051-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:38:43.335-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.307 seconds
[2023-07-15T16:40:06.333-0400] {processor.py:157} INFO - Started process (PID=35208) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:40:06.336-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:40:06.336-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:40:06.336-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:40:06.357-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:40:06.356-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:40:06.357-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:40:06.357-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:40:06.357-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:40:06.623-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T16:41:51.448-0400] {processor.py:157} INFO - Started process (PID=35378) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:41:51.450-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:41:51.450-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:41:51.450-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:41:51.472-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:41:51.472-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:41:51.472-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:41:51.472-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:41:51.472-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:41:51.758-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.311 seconds
[2023-07-15T16:43:13.353-0400] {processor.py:157} INFO - Started process (PID=35557) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:43:13.357-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:43:13.357-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:43:13.357-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:43:13.377-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:43:13.377-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:43:13.377-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:43:13.377-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:43:13.377-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:43:13.662-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.310 seconds
[2023-07-15T16:44:52.063-0400] {processor.py:157} INFO - Started process (PID=35732) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:44:52.067-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:44:52.067-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:44:52.067-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:44:52.092-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:44:52.091-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:44:52.092-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:44:52.092-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:44:52.092-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:44:52.378-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.315 seconds
[2023-07-15T16:45:55.018-0400] {processor.py:157} INFO - Started process (PID=35847) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:45:55.021-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:45:55.021-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:45:55.021-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:45:55.042-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:45:55.041-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:45:55.042-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:45:55.042-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:45:55.042-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:45:55.325-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.307 seconds
[2023-07-15T16:54:33.782-0400] {processor.py:157} INFO - Started process (PID=36421) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:54:33.784-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:54:33.785-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:54:33.785-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:54:33.806-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:54:33.806-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:54:33.807-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:54:33.806-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:54:33.807-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:54:34.094-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.312 seconds
[2023-07-15T16:56:05.453-0400] {processor.py:157} INFO - Started process (PID=36567) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:56:05.456-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:56:05.457-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:56:05.457-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:56:05.481-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:56:05.481-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:56:05.481-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:56:05.481-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:56:05.481-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:56:05.803-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.351 seconds
[2023-07-15T16:57:42.771-0400] {processor.py:157} INFO - Started process (PID=36733) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:57:42.774-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:57:42.774-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:57:42.774-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:57:42.794-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:57:42.794-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:57:42.795-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:57:42.795-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:57:42.795-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:57:43.058-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.288 seconds
[2023-07-15T16:59:23.608-0400] {processor.py:157} INFO - Started process (PID=36888) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:59:23.610-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T16:59:23.610-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:59:23.610-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:59:23.631-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:59:23.630-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T16:59:23.631-0400] {logging_mixin.py:150} INFO - [2023-07-15T16:59:23.631-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T16:59:23.631-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T16:59:23.893-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.286 seconds
[2023-07-15T17:00:50.002-0400] {processor.py:157} INFO - Started process (PID=37021) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:00:50.008-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:00:50.008-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:00:50.008-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:00:50.035-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:00:50.035-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:00:50.035-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:00:50.035-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:00:50.036-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:00:50.336-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.335 seconds
[2023-07-15T17:02:37.657-0400] {processor.py:157} INFO - Started process (PID=37188) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:02:37.660-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:02:37.661-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:02:37.661-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:02:37.681-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:02:37.681-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:02:37.681-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:02:37.681-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:02:37.681-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:02:37.947-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T17:04:17.542-0400] {processor.py:157} INFO - Started process (PID=37343) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:04:17.544-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:04:17.545-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:04:17.545-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:04:17.565-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:04:17.564-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:04:17.565-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:04:17.565-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:04:17.565-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:04:17.831-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T17:05:59.653-0400] {processor.py:157} INFO - Started process (PID=37505) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:05:59.656-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:05:59.657-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:05:59.657-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:05:59.676-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:05:59.676-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:05:59.676-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:05:59.676-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:05:59.676-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:05:59.940-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.287 seconds
[2023-07-15T17:07:38.851-0400] {processor.py:157} INFO - Started process (PID=37662) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:07:38.854-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:07:38.855-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:07:38.855-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:07:38.875-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:07:38.875-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:07:38.875-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:07:38.875-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:07:38.875-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:07:39.143-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.292 seconds
[2023-07-15T17:09:25.228-0400] {processor.py:157} INFO - Started process (PID=37920) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:09:25.231-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:09:25.232-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:09:25.232-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:09:25.252-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:09:25.252-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:09:25.252-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:09:25.252-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:09:25.252-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:09:25.519-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-07-15T17:11:01.821-0400] {processor.py:157} INFO - Started process (PID=38070) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:11:01.824-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:11:01.825-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:11:01.824-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:11:01.844-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:11:01.844-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:11:01.844-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:11:01.844-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:11:01.844-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:11:02.107-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.286 seconds
[2023-07-15T17:12:45.167-0400] {processor.py:157} INFO - Started process (PID=38230) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:12:45.169-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:12:45.169-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:12:45.169-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:12:45.189-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:12:45.189-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:12:45.189-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:12:45.189-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:12:45.189-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:12:45.452-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.286 seconds
[2023-07-15T17:14:30.722-0400] {processor.py:157} INFO - Started process (PID=38387) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:14:30.725-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:14:30.725-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:14:30.725-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:14:30.745-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:14:30.745-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:14:30.745-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:14:30.745-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:14:30.745-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:14:31.007-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.285 seconds
[2023-07-15T17:16:16.091-0400] {processor.py:157} INFO - Started process (PID=38552) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:16:16.094-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:16:16.094-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:16:16.094-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:16:16.115-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:16:16.114-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:16:16.115-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:16:16.115-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:16:16.115-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:16:16.381-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-07-15T17:18:02.474-0400] {processor.py:157} INFO - Started process (PID=38711) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:18:02.476-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:18:02.476-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:18:02.476-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:18:02.496-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:18:02.496-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:18:02.496-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:18:02.496-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:18:02.496-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:18:02.760-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.286 seconds
[2023-07-15T17:19:41.139-0400] {processor.py:157} INFO - Started process (PID=38867) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:19:41.142-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:19:41.142-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:19:41.142-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:19:41.163-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:19:41.163-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:19:41.164-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:19:41.164-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:19:41.164-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:19:41.433-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.294 seconds
[2023-07-15T17:21:26.315-0400] {processor.py:157} INFO - Started process (PID=39028) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:21:26.319-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:21:26.319-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:21:26.319-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:21:26.338-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:21:26.338-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:21:26.338-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:21:26.338-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:21:26.338-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:21:26.604-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T17:23:09.637-0400] {processor.py:157} INFO - Started process (PID=39186) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:23:09.639-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:23:09.639-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:23:09.639-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:23:09.659-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:23:09.658-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:23:09.659-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:23:09.659-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:23:09.659-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:23:09.922-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.286 seconds
[2023-07-15T17:24:51.296-0400] {processor.py:157} INFO - Started process (PID=39341) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:24:51.299-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:24:51.299-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:24:51.299-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:24:51.319-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:24:51.319-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:24:51.319-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:24:51.319-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:24:51.319-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:24:51.582-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.286 seconds
[2023-07-15T17:26:30.676-0400] {processor.py:157} INFO - Started process (PID=39495) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:26:30.678-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:26:30.678-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:26:30.678-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:26:30.698-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:26:30.698-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:26:30.698-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:26:30.698-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:26:30.698-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:26:30.966-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-07-15T17:28:13.822-0400] {processor.py:157} INFO - Started process (PID=39652) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:28:13.824-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:28:13.824-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:28:13.824-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:28:13.844-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:28:13.844-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:28:13.844-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:28:13.844-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:28:13.844-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:28:14.111-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.289 seconds
[2023-07-15T17:29:56.629-0400] {processor.py:157} INFO - Started process (PID=39809) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:29:56.631-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:29:56.632-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:29:56.632-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:29:56.651-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:29:56.651-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:29:56.651-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:29:56.651-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:29:56.652-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:29:56.919-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T17:36:28.803-0400] {processor.py:157} INFO - Started process (PID=39996) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:36:28.806-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:36:28.806-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:36:28.806-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:36:28.826-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:36:28.826-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:36:28.826-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:36:28.826-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:36:28.826-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:36:29.092-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.289 seconds
[2023-07-15T17:41:23.765-0400] {processor.py:157} INFO - Started process (PID=40201) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:41:23.768-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:41:23.768-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:41:23.768-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:41:23.789-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:41:23.789-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:41:23.789-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:41:23.789-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:41:23.789-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:41:24.068-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.303 seconds
[2023-07-15T17:43:18.222-0400] {processor.py:157} INFO - Started process (PID=40418) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:43:18.225-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:43:18.225-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:43:18.225-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:43:18.246-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:43:18.245-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:43:18.246-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:43:18.246-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:43:18.246-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:43:18.512-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T17:45:04.643-0400] {processor.py:157} INFO - Started process (PID=40589) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:45:04.646-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:45:04.646-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:45:04.646-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:45:04.666-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:45:04.666-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:45:04.666-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:45:04.666-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:45:04.666-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:45:04.930-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.287 seconds
[2023-07-15T17:46:46.814-0400] {processor.py:157} INFO - Started process (PID=40756) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:46:46.817-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:46:46.818-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:46:46.817-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:46:46.839-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:46:46.839-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:46:46.839-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:46:46.839-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:46:46.839-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:46:47.104-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-07-15T17:48:26.553-0400] {processor.py:157} INFO - Started process (PID=40917) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:48:26.557-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:48:26.557-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:48:26.557-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:48:26.577-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:48:26.577-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:48:26.577-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:48:26.577-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:48:26.577-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:48:26.840-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.287 seconds
[2023-07-15T17:50:10.419-0400] {processor.py:157} INFO - Started process (PID=41084) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:50:10.422-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:50:10.422-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:50:10.422-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:50:10.442-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:50:10.442-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:50:10.442-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:50:10.442-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:50:10.442-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:50:10.712-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.293 seconds
[2023-07-15T17:52:02.949-0400] {processor.py:157} INFO - Started process (PID=41269) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:52:02.954-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:52:02.955-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:52:02.955-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:52:02.980-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:52:02.980-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:52:02.980-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:52:02.980-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:52:02.980-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:52:03.290-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.341 seconds
[2023-07-15T17:53:51.207-0400] {processor.py:157} INFO - Started process (PID=41438) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:53:51.211-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:53:51.211-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:53:51.211-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:53:51.232-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:53:51.232-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:53:51.232-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:53:51.232-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:53:51.232-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:53:51.503-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.296 seconds
[2023-07-15T17:55:39.953-0400] {processor.py:157} INFO - Started process (PID=41608) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:55:39.957-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:55:39.957-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:55:39.957-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:55:39.978-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:55:39.978-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:55:39.978-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:55:39.978-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:55:39.978-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:55:40.258-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.305 seconds
[2023-07-15T17:57:28.437-0400] {processor.py:157} INFO - Started process (PID=41772) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:57:28.439-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:57:28.440-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:57:28.440-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:57:28.459-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:57:28.459-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:57:28.459-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:57:28.459-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:57:28.460-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:57:28.725-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.289 seconds
[2023-07-15T17:59:16.618-0400] {processor.py:157} INFO - Started process (PID=41935) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:59:16.621-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T17:59:16.621-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:59:16.621-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:59:16.643-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:59:16.643-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T17:59:16.644-0400] {logging_mixin.py:150} INFO - [2023-07-15T17:59:16.644-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T17:59:16.644-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T17:59:16.943-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.325 seconds
[2023-07-15T18:01:09.580-0400] {processor.py:157} INFO - Started process (PID=42106) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:01:09.582-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:01:09.582-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:01:09.582-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:01:09.603-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:01:09.603-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:01:09.603-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:01:09.603-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:01:09.603-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:01:09.892-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.312 seconds
[2023-07-15T18:02:55.479-0400] {processor.py:157} INFO - Started process (PID=42271) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:02:55.481-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:02:55.481-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:02:55.481-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:02:55.501-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:02:55.501-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:02:55.501-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:02:55.501-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:02:55.501-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:02:55.782-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.304 seconds
[2023-07-15T18:04:48.661-0400] {processor.py:157} INFO - Started process (PID=42459) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:04:48.664-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:04:48.664-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:04:48.664-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:04:48.696-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:04:48.695-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:04:48.696-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:04:48.696-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:04:48.696-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:04:49.049-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.389 seconds
[2023-07-15T18:06:35.459-0400] {processor.py:157} INFO - Started process (PID=42644) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:06:35.463-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:06:35.463-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:06:35.463-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:06:35.482-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:06:35.482-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:06:35.482-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:06:35.482-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:06:35.483-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:06:35.751-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.292 seconds
[2023-07-15T18:08:20.510-0400] {processor.py:157} INFO - Started process (PID=42825) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:08:20.513-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:08:20.513-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:08:20.513-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:08:20.535-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:08:20.534-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:08:20.535-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:08:20.535-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:08:20.535-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:08:20.804-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.294 seconds
[2023-07-15T18:10:14.790-0400] {processor.py:157} INFO - Started process (PID=43014) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:10:14.792-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:10:14.793-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:10:14.793-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:10:14.844-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:10:14.843-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:10:14.844-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:10:14.844-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:10:14.844-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:10:15.138-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.349 seconds
[2023-07-15T18:12:08.535-0400] {processor.py:157} INFO - Started process (PID=43201) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:12:08.538-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:12:08.538-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:12:08.538-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:12:08.559-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:12:08.559-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:12:08.559-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:12:08.559-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:12:08.559-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:12:08.826-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.292 seconds
[2023-07-15T18:13:58.400-0400] {processor.py:157} INFO - Started process (PID=43380) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:13:58.403-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:13:58.404-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:13:58.404-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:13:58.425-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:13:58.425-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:13:58.425-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:13:58.425-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:13:58.425-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:13:58.696-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.297 seconds
[2023-07-15T18:15:47.504-0400] {processor.py:157} INFO - Started process (PID=43570) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:15:47.507-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:15:47.507-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:15:47.507-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:15:47.529-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:15:47.528-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:15:47.529-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:15:47.529-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:15:47.529-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:15:47.811-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.307 seconds
[2023-07-15T18:17:42.722-0400] {processor.py:157} INFO - Started process (PID=43746) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:17:42.725-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:17:42.725-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:17:42.725-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:17:42.749-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:17:42.749-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:17:42.749-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:17:42.749-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:17:42.750-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:17:43.055-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.334 seconds
[2023-07-15T18:19:33.967-0400] {processor.py:157} INFO - Started process (PID=43927) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:19:33.971-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:19:33.971-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:19:33.971-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:19:33.994-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:19:33.994-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:19:33.994-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:19:33.994-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:19:33.994-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:19:34.297-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.330 seconds
[2023-07-15T18:21:25.936-0400] {processor.py:157} INFO - Started process (PID=44101) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:21:25.939-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:21:25.939-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:21:25.939-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:21:25.962-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:21:25.962-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:21:25.962-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:21:25.962-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:21:25.962-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:21:26.267-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.332 seconds
[2023-07-15T18:23:21.523-0400] {processor.py:157} INFO - Started process (PID=44296) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:23:21.526-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:23:21.527-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:23:21.527-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:23:21.548-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:23:21.548-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:23:21.548-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:23:21.548-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:23:21.549-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:23:21.830-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.307 seconds
[2023-07-15T18:25:08.940-0400] {processor.py:157} INFO - Started process (PID=44459) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:25:08.942-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:25:08.943-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:25:08.943-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:25:08.964-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:25:08.964-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:25:08.964-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:25:08.964-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:25:08.964-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:25:09.241-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.301 seconds
[2023-07-15T18:26:55.466-0400] {processor.py:157} INFO - Started process (PID=44624) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:26:55.468-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:26:55.468-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:26:55.468-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:26:55.488-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:26:55.488-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:26:55.488-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:26:55.488-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:26:55.488-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:26:55.756-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-07-15T18:28:35.785-0400] {processor.py:157} INFO - Started process (PID=44780) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:28:35.789-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:28:35.789-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:28:35.789-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:28:35.810-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:28:35.810-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:28:35.810-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:28:35.810-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:28:35.810-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:28:36.094-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.309 seconds
[2023-07-15T18:30:20.511-0400] {processor.py:157} INFO - Started process (PID=44939) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:30:20.514-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:30:20.515-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:30:20.515-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:30:20.535-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:30:20.535-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:30:20.536-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:30:20.536-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:30:20.536-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:30:20.802-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-07-15T18:32:04.164-0400] {processor.py:157} INFO - Started process (PID=45096) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:32:04.168-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:32:04.168-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:32:04.168-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:32:04.188-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:32:04.188-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:32:04.188-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:32:04.188-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:32:04.188-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:32:04.461-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.297 seconds
[2023-07-15T18:33:51.376-0400] {processor.py:157} INFO - Started process (PID=45257) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:33:51.379-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:33:51.379-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:33:51.379-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:33:51.400-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:33:51.400-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:33:51.400-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:33:51.400-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:33:51.400-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:33:51.666-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T18:36:46.778-0400] {processor.py:157} INFO - Started process (PID=45432) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:36:46.781-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:36:46.781-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:36:46.781-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:36:46.804-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:36:46.804-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:36:46.805-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:36:46.804-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:36:46.805-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:36:47.114-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.336 seconds
[2023-07-15T18:38:50.648-0400] {processor.py:157} INFO - Started process (PID=45633) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:38:50.652-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:38:50.652-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:38:50.652-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:38:50.673-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:38:50.673-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:38:50.674-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:38:50.674-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:38:50.674-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:38:50.950-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.302 seconds
[2023-07-15T18:40:37.323-0400] {processor.py:157} INFO - Started process (PID=45801) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:40:37.327-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:40:37.327-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:40:37.327-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:40:37.350-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:40:37.350-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:40:37.350-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:40:37.350-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:40:37.350-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:40:37.646-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.323 seconds
[2023-07-15T18:42:32.759-0400] {processor.py:157} INFO - Started process (PID=45977) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:42:32.762-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:42:32.762-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:42:32.762-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:42:32.784-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:42:32.784-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:42:32.784-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:42:32.784-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:42:32.785-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:42:33.064-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.306 seconds
[2023-07-15T18:44:30.874-0400] {processor.py:157} INFO - Started process (PID=46175) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:44:30.877-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:44:30.877-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:44:30.877-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:44:30.908-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:44:30.907-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:44:30.908-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:44:30.908-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:44:30.908-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:44:31.214-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.340 seconds
[2023-07-15T18:46:18.653-0400] {processor.py:157} INFO - Started process (PID=46348) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:46:18.657-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:46:18.657-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:46:18.657-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:46:18.679-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:46:18.678-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:46:18.679-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:46:18.679-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:46:18.679-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:46:18.954-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.301 seconds
[2023-07-15T18:48:04.782-0400] {processor.py:157} INFO - Started process (PID=46509) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:48:04.786-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:48:04.786-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:48:04.786-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:48:04.808-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:48:04.807-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:48:04.808-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:48:04.808-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:48:04.808-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:48:05.084-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.303 seconds
[2023-07-15T18:49:52.348-0400] {processor.py:157} INFO - Started process (PID=46676) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:49:52.352-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:49:52.352-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:49:52.352-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:49:52.372-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:49:52.372-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:49:52.372-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:49:52.372-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:49:52.372-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:49:52.649-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.301 seconds
[2023-07-15T18:51:36.769-0400] {processor.py:157} INFO - Started process (PID=46835) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:51:36.773-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:51:36.773-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:51:36.773-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:51:36.796-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:51:36.796-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:51:36.796-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:51:36.796-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:51:36.796-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:51:37.102-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.333 seconds
[2023-07-15T18:53:21.209-0400] {processor.py:157} INFO - Started process (PID=46993) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:53:21.212-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:53:21.212-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:53:21.212-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:53:21.234-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:53:21.234-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:53:21.234-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:53:21.234-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:53:21.234-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:53:21.507-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.299 seconds
[2023-07-15T18:55:13.962-0400] {processor.py:157} INFO - Started process (PID=47204) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:55:13.965-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:55:13.965-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:55:13.965-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:55:13.986-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:55:13.986-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:55:13.987-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:55:13.987-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:55:13.987-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:55:14.259-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.297 seconds
[2023-07-15T18:57:08.752-0400] {processor.py:157} INFO - Started process (PID=47385) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:57:08.755-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:57:08.755-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:57:08.755-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:57:08.777-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:57:08.776-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:57:08.777-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:57:08.777-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:57:08.777-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:57:09.049-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.298 seconds
[2023-07-15T18:58:58.794-0400] {processor.py:157} INFO - Started process (PID=47566) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:58:58.796-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T18:58:58.797-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:58:58.796-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:58:58.820-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:58:58.820-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T18:58:58.820-0400] {logging_mixin.py:150} INFO - [2023-07-15T18:58:58.820-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T18:58:58.820-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T18:58:59.130-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.337 seconds
[2023-07-15T19:00:46.703-0400] {processor.py:157} INFO - Started process (PID=47746) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:00:46.707-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:00:46.707-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:00:46.707-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:00:46.729-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:00:46.729-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:00:46.729-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:00:46.729-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:00:46.729-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:00:47.007-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.304 seconds
[2023-07-15T19:02:31.556-0400] {processor.py:157} INFO - Started process (PID=47905) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:02:31.559-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:02:31.559-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:02:31.559-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:02:31.581-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:02:31.580-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:02:31.581-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:02:31.581-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:02:31.581-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:02:31.862-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.307 seconds
[2023-07-15T19:04:19.783-0400] {processor.py:157} INFO - Started process (PID=48075) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:04:19.787-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:04:19.787-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:04:19.787-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:04:19.810-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:04:19.809-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:04:19.810-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:04:19.810-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:04:19.810-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:04:20.100-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.317 seconds
[2023-07-15T19:06:14.491-0400] {processor.py:157} INFO - Started process (PID=48264) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:06:14.494-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:06:14.494-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:06:14.494-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:06:14.520-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:06:14.518-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:06:14.521-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:06:14.520-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:06:14.521-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:06:14.831-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.341 seconds
[2023-07-15T19:08:06.485-0400] {processor.py:157} INFO - Started process (PID=48438) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:08:06.487-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:08:06.488-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:08:06.488-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:08:06.511-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:08:06.510-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:08:06.511-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:08:06.511-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:08:06.511-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:08:06.821-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.337 seconds
[2023-07-15T19:10:04.949-0400] {processor.py:157} INFO - Started process (PID=48619) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:10:04.952-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:10:04.952-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:10:04.952-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:10:04.974-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:10:04.974-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:10:04.974-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:10:04.974-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:10:04.974-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:10:05.253-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.304 seconds
[2023-07-15T19:11:55.830-0400] {processor.py:157} INFO - Started process (PID=48789) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:11:55.833-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:11:55.833-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:11:55.833-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:11:55.853-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:11:55.852-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:11:55.853-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:11:55.853-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:11:55.853-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:11:56.118-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.288 seconds
[2023-07-15T19:13:41.460-0400] {processor.py:157} INFO - Started process (PID=48951) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:13:41.462-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:13:41.462-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:13:41.462-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:13:41.482-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:13:41.482-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:13:41.482-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:13:41.482-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:13:41.482-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:13:41.748-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.289 seconds
[2023-07-15T19:15:28.743-0400] {processor.py:157} INFO - Started process (PID=49117) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:15:28.745-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:15:28.746-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:15:28.746-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:15:28.768-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:15:28.768-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:15:28.768-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:15:28.768-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:15:28.768-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:15:29.063-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.320 seconds
[2023-07-15T19:17:13.848-0400] {processor.py:157} INFO - Started process (PID=49284) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:17:13.851-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:17:13.851-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:17:13.851-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:17:13.874-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:17:13.874-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:17:13.874-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:17:13.874-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:17:13.874-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:17:14.154-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.307 seconds
[2023-07-15T19:19:00.246-0400] {processor.py:157} INFO - Started process (PID=49446) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:19:00.248-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:19:00.248-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:19:00.248-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:19:00.268-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:19:00.268-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:19:00.268-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:19:00.268-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:19:00.268-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:19:00.541-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.296 seconds
[2023-07-15T19:20:37.047-0400] {processor.py:157} INFO - Started process (PID=49601) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:20:37.049-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:20:37.050-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:20:37.050-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:20:37.069-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:20:37.069-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:20:37.070-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:20:37.069-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:20:37.070-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:20:37.337-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T19:24:02.184-0400] {processor.py:157} INFO - Started process (PID=49929) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:24:02.186-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:24:02.186-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:24:02.186-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:24:02.206-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:24:02.206-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:24:02.206-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:24:02.206-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:24:02.206-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:24:02.472-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.289 seconds
[2023-07-15T19:25:49.108-0400] {processor.py:157} INFO - Started process (PID=50128) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:25:49.111-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:25:49.111-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:25:49.111-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:25:49.135-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:25:49.135-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:25:49.135-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:25:49.135-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:25:49.135-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:25:49.432-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.325 seconds
[2023-07-15T19:27:33.356-0400] {processor.py:157} INFO - Started process (PID=50326) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:27:33.360-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:27:33.360-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:27:33.360-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:27:33.384-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:27:33.384-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:27:33.384-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:27:33.384-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:27:33.384-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:27:33.686-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.330 seconds
[2023-07-15T19:31:23.249-0400] {processor.py:157} INFO - Started process (PID=50699) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:31:23.252-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:31:23.252-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:31:23.252-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:31:23.274-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:31:23.274-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:31:23.274-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:31:23.274-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:31:23.274-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:31:23.573-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.324 seconds
[2023-07-15T19:32:48.573-0400] {processor.py:157} INFO - Started process (PID=50833) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:32:48.576-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:32:48.576-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:32:48.576-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:32:48.599-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:32:48.599-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:32:48.599-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:32:48.599-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:32:48.600-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:32:48.906-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.334 seconds
[2023-07-15T19:34:34.303-0400] {processor.py:157} INFO - Started process (PID=51013) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:34:34.306-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:34:34.307-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:34:34.307-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:34:34.331-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:34:34.330-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:34:34.331-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:34:34.331-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:34:34.332-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:34:34.633-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.331 seconds
[2023-07-15T19:36:22.568-0400] {processor.py:157} INFO - Started process (PID=51211) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:36:22.572-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:36:22.572-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:36:22.572-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:36:22.594-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:36:22.594-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:36:22.594-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:36:22.594-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:36:22.594-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:36:22.882-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.314 seconds
[2023-07-15T19:38:07.625-0400] {processor.py:157} INFO - Started process (PID=51385) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:38:07.629-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:38:07.629-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:38:07.629-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:38:07.651-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:38:07.651-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:38:07.651-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:38:07.651-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:38:07.651-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:38:07.928-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.304 seconds
[2023-07-15T19:39:50.184-0400] {processor.py:157} INFO - Started process (PID=51544) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:39:50.186-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:39:50.187-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:39:50.187-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:39:50.206-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:39:50.206-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:39:50.206-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:39:50.206-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:39:50.207-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:39:50.472-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.288 seconds
[2023-07-15T19:41:34.135-0400] {processor.py:157} INFO - Started process (PID=51709) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:41:34.138-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:41:34.138-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:41:34.138-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:41:34.158-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:41:34.158-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:41:34.158-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:41:34.158-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:41:34.158-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:41:34.431-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.296 seconds
[2023-07-15T19:43:11.732-0400] {processor.py:157} INFO - Started process (PID=51861) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:43:11.734-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:43:11.734-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:43:11.734-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:43:11.754-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:43:11.754-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:43:11.754-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:43:11.754-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:43:11.754-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:43:12.028-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.296 seconds
[2023-07-15T19:44:55.258-0400] {processor.py:157} INFO - Started process (PID=52031) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:44:55.261-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:44:55.261-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:44:55.261-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:44:55.281-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:44:55.280-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:44:55.281-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:44:55.281-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:44:55.281-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:44:55.546-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.288 seconds
[2023-07-15T19:46:33.900-0400] {processor.py:157} INFO - Started process (PID=52184) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:46:33.903-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:46:33.903-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:46:33.903-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:46:33.924-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:46:33.924-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:46:33.924-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:46:33.924-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:46:33.924-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:46:34.194-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.294 seconds
[2023-07-15T19:48:14.236-0400] {processor.py:157} INFO - Started process (PID=52343) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:48:14.238-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:48:14.238-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:48:14.238-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:48:14.258-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:48:14.258-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:48:14.258-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:48:14.258-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:48:14.258-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:48:14.528-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.293 seconds
[2023-07-15T19:49:55.749-0400] {processor.py:157} INFO - Started process (PID=52510) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:49:55.752-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:49:55.752-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:49:55.752-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:49:55.772-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:49:55.772-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:49:55.772-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:49:55.772-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:49:55.772-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:49:56.038-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T19:51:33.128-0400] {processor.py:157} INFO - Started process (PID=52662) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:51:33.130-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:51:33.131-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:51:33.131-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:51:33.150-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:51:33.150-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:51:33.151-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:51:33.150-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:51:33.151-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:51:33.417-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.290 seconds
[2023-07-15T19:53:15.940-0400] {processor.py:157} INFO - Started process (PID=52833) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:53:15.943-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:53:15.943-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:53:15.943-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:53:15.963-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:53:15.963-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:53:15.963-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:53:15.963-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:53:15.963-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:53:16.240-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.300 seconds
[2023-07-15T19:56:44.208-0400] {processor.py:157} INFO - Started process (PID=53164) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:56:44.210-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:56:44.210-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:56:44.210-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:56:44.230-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:56:44.230-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:56:44.230-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:56:44.230-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:56:44.230-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:56:44.506-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.298 seconds
[2023-07-15T19:58:12.798-0400] {processor.py:157} INFO - Started process (PID=53336) to work on /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:58:12.801-0400] {processor.py:826} INFO - Processing file /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-15T19:58:12.801-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:58:12.801-0400] {dagbag.py:541} INFO - Filling up the DagBag from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:58:12.824-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:58:12.824-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-15T19:58:12.824-0400] {logging_mixin.py:150} INFO - [2023-07-15T19:58:12.824-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-15T19:58:12.825-0400] {processor.py:838} WARNING - No viable dags retrieved from /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-15T19:58:13.109-0400] {processor.py:179} INFO - Processing /Users/pratikdomadiya/opt/anaconda3/envs/python39/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.312 seconds
